"""create log analyzer tables

Revision ID: 6bb2b39af299
Revises:
Create Date: 2025-12-29 17:29:10.224630

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bb2b39af299"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "directories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_index(op.f("ix_directories_id"), "directories", ["id"], unique=False)
    op.create_table(
        "log_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("directory_id", sa.Integer(), nullable=True),
        sa.Column(
            "processed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["directory_id"],
            ["directories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_log_files_id"), "log_files", ["id"], unique=False)
    op.create_table(
        "log_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("level", sa.String(), nullable=True),
        sa.Column("component", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["log_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_log_entries_component"), "log_entries", ["component"], unique=False
    )
    op.create_index(op.f("ix_log_entries_id"), "log_entries", ["id"], unique=False)
    op.create_index(
        op.f("ix_log_entries_level"), "log_entries", ["level"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_log_entries_level"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_id"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_component"), table_name="log_entries")
    op.drop_table("log_entries")
    op.drop_index(op.f("ix_log_files_id"), table_name="log_files")
    op.drop_table("log_files")
    op.drop_index(op.f("ix_directories_id"), table_name="directories")
    op.drop_table("directories")
    # ### end Alembic commands ###
